name: girscope
description: "GIRScope - A read-only mobile app for GIR W150 fuel management system"
publish_to: "none"
version: 1.0.2+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.1
  intl: ^0.19.0
  supabase_flutter: ^2.5.0
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.2
  mailer: ^6.1.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/