name: girscope
description: "GIRScope - A read-only mobile app for GIR W150 fuel management system"
publish_to: "none"
version: 1.0.6+6

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.1
  intl: ^0.19.0
  supabase_flutter: ^2.5.0
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  pinput: ^5.0.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.4
  path: ^1.9.0
  cached_network_image: ^3.4.1
  smart_auth: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
